Repository iri-wa-7team/iri-wa, pull requests merged in 2024-12, with the labels that each got.

#6 style:인플루언서 페이지 메인섹션
  public/assets/images/apple.svg
  src/app/influencer/_view/mainSection.tsx
  src/app/influencer/layout.tsx
  src/app/influencer/page.tsx
Labels: 우선순위: 🟢 낮음, 💄style

#8 Style/인플루언서 페이지 중간섹션 ui 작업
  package.json
  public/assets/images/qr_appstore_popup.svg
  public/assets/images/qr_playstore_popup.svg
  public/assets/images/x.svg
  src/app/influencer/_view/introduction.tsx
  src/app/influencer/_view/product.tsx
  src/app/influencer/components/CampaignModal.tsx
  src/app/influencer/components/InfluencerCard.tsx
  src/app/influencer/page.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: 우선순위: 🟡 중간, 💄style

#10 feat: 상단 navBar 추가
  package-lock.json
  package.json
  public/assets/images/navMenu.svg
  src/app/advertiser/page.tsx
  src/app/influencer/layout.tsx
  src/components/buttons/Button.tsx
  src/components/buttons/HomeButton.tsx
  src/components/buttons/buttonStyle.ts
  src/components/dropdown/Dropdown.tsx
  src/components/navbar/AdvNavBar.tsx
  src/components/navbar/InfluNavBar.tsx
  src/types/types.ts
  tailwind.config.ts
Labels: 우선순위: 🟡 중간, 💄style

#14 deploy/네트리파이 배포관련 라이브러리 설치 및 파일 생성
  netlify.toml
  next.config.mjs
  package-lock.json
  package.json
Labels: 🚀 Deploy

#17 style/ 웹 사이트 사이즈 줄었을때 자연스럽게 반영되도록 적용
  next.config.mjs
  public/assets/images/qr_appstore.png
  public/assets/images/qr_playstore.png
  src/app/influencer/_view/introduction.tsx
  src/app/influencer/_view/mainSection.tsx
  src/app/influencer/_view/product.tsx
  src/app/influencer/components/CampaignModal.tsx
  src/app/influencer/components/InfluencerCard.tsx
  src/app/influencer/layout.tsx
  src/app/influencer/page.tsx
Labels: 우선순위: 🟡 중간, 💄style, ♻️ Refactor

#20 Style/advertiser 페이지 섹션 추가
  public/assets/images/list.svg
  src/app/advertiser/components/about/AboutItems.tsx
  src/app/advertiser/components/about/AboutSection.tsx
  src/app/advertiser/components/about/Slide.tsx
  src/app/advertiser/components/about/Slides.tsx
  src/app/advertiser/components/intro/IntroSection.tsx
  src/app/advertiser/components/performance/PerformanceSection.tsx
  src/app/advertiser/components/video/Video.tsx
  src/app/advertiser/page.tsx
  src/components/buttons/HomeButton.tsx
  src/components/buttons/buttonStyle.ts
  src/components/dropdown/Dropdown.tsx
  src/components/navbar/AdvNavBar.tsx
  src/hooks/useScroll.tsx
  tsconfig.json
Labels: 우선순위: 🟢 낮음, 💄style

#24 feat/logoline clear
  public/assets/images/LG_AVANI.svg
  public/assets/images/LG_BLUEOCEAN.svg
  public/assets/images/LG_CAPPUCCINO.svg
  public/assets/images/LG_COURTYARD.svg
  public/assets/images/LG_HOTELFORET.svg
  public/assets/images/LG_HOTELFORETPRE.svg
  public/assets/images/LG_HOTELKOREANA.svg
  public/assets/images/LG_IBISSTYLES.svg
  public/assets/images/LG_KLOOK.svg
  public/assets/images/LG_LOTTEHOTELS.svg
  public/assets/images/LG_NOVOTEL.svg
  public/assets/images/LG_PHOENIX.svg
  public/assets/images/LG_THEFIRST70.svg
  public/assets/images/LG_TRIPCOM.svg
  public/assets/images/LG_YANOLJA.svg
  public/assets/images/LG_YEOSU.svg
  public/assets/images/THEISLANDBLUE.svg
  src/app/advertiser/components/logoline/LogoLine.tsx
  src/app/advertiser/page.tsx
  src/app/layout.tsx
  tailwind.config.ts
Labels: ✨Feature

#27 로고 중간 큰 컴포넌트 구현
  public/assets/images/Logo_Sponsor.svg
  src/app/advertiser/components/cert/Cert.tsx
  src/app/advertiser/page.tsx
Labels: ✨Feature

#29 [Feat]MoreService clear
  public/assets/images/Service_Black.svg
  public/assets/images/Service_Macro.svg
  public/assets/images/Service_Pakage.svg
  public/assets/images/Service_Sales.svg
  src/app/advertiser/components/services/Services.tsx
  src/app/advertiser/page.tsx
Labels: ✨Feature

#31 [FEAT] question 컴포넌트 클리어
  src/app/advertiser/components/question/Question.tsx
  src/app/advertiser/page.tsx
Labels: ✨Feature

#36 [Feat] 문의사항 컴포넌트 구현
  src/app/advertiser/components/inquiry/Inquiry.tsx
  src/app/advertiser/page.tsx
Labels: ✨Feature

#41 [Feat]반응형 작업
  src/app/advertiser/components/cert/Cert.tsx
  src/app/advertiser/components/hotelreview/HotelReview.tsx
  src/app/advertiser/components/logoline/LogoLine.tsx
  src/app/advertiser/components/question/Question.tsx
  src/app/advertiser/components/services/Services.tsx
Labels: ✨Feature
